### ISSUE TITLE
Add a way to completely disable logging

### ISSUE THREAD

**Issue by dimsuz** [sergejsha/logger#1]
It is useful to have a way to completely disable logging, for example, in release builds.

If I understood the source code correctly, currently `getMessage()` is _not_ evaluated only if a log level is too high for it. There's no way to have it _not_ to be evaluated _ever_. Even if I don't add any sinks, it will still be evaluated and then sent to `sinks.forEach { ... }`. So the "lazyiness" promise is broken in this case.

In my similar toy library I have 

```kotlin
enum class PriorityLogging {  Enabled,  Disabled }

fun isLoggable(level: LogLevel): PriorityLogging
```

which separately configures if a certain log level will ever be active (+ have messages evaluated).

And then in release builds I can simply disable logging of all levels.

But maybe you would go some other way here (having no sinks => no evaluation?)

**Comment by sergejsha** [comment]
Do you have any real live example of when loggability of each log level needs to be configured separately?

**Comment by sergejsha** [comment]
In the current design, loggability is configured using `LogLevel` as follows:

```kotlin
initializeLogger {
    loggableLevel = LogLevel.Debug
}
```

- When set to `LogLevel.Debug`, messages of all log levels with higher weight are evaluated and send to sinks. This is "enable all" configuration.
- When set to the highest weight `LogLevel.Error`, only error messages are evaluated. This is "disable all but errors" configuration.
- When set to anything in between, only message of the set and higher levels will be logger.

Here are tests for the contract: https://github.com/sergejsha/logger/blob/5ab28fc421608f63f7eeb52955775004494fc4f1/logger/src/commonTest/kotlin/de/halfbit/logger/LoggableLevelTest.kt

The only missing part would be to also disable processing of errors message. The question is, however, whether "disable all" is a usable/usefull configuration for an app? If an app reports no errors, the app cannot be improved, right?

**Comment by dimsuz** [comment]
> Do you have any real live example of when loggability of each log level needs to be configured separately?

Not really, I guess this was a not very good design on my part :)

What I actually want is the ability to disable logging completely (along with eval of lazy message lambdas).

>  If an app reports no errors, the app cannot be improved, right?

Not really, the app can have different means of gathering feedback: for example in the form of analytics, custom binary state snaphots, remote server logging or whatever else.

The usecase which I had is when developing banking apps, for example, there might be a request to 100% disable all logging to avoid accidental leaks of some info or other similar security measures (whether this is actually helps is debatable, but sometimes this comes as a requirement).

**Comment by sergejsha** [comment]
@dimsuz The change above let you use `LoggableLevel.Nothing` in the logger configuration for disabling all logs (of any log levels). It should resolves the issue. Does it?

**Comment by dimsuz** [comment]
Nice, it does, thanks! This is also more understandable naming wise, I always get confused when I think about log-level heirarchy (e.g. what will be logged for this log level), this approach looks better!

**Comment by sergejsha** [comment]
Awesome! Thank you :)
