### ISSUE TITLE
Move to an 'official' permissive license?

### ISSUE THREAD

**Issue by StefMa** [sergejsha/logger#4]
Right now this project is licensed under a "Custom License".
https://github.com/sergejsha/logger/blob/6f8778dde1759853396ca0fcef5423e3c2af225b/convention-plugins/src/main/kotlin/module.publication.gradle.kts#L45-L46

Unfortunately, this leads in some projects to the case that this project can't be used as they might use tools like [Licensee](https://github.com/cashapp/licensee) to check for an permissive license.

As I understand your current "custom license" there are no real differences to the MIT.
Expect of the fact that copies of that should use the same license, right?
Not sure if there are any other license that make sure that this is the case.

However, are there plans to move to an official license instead of a using a custom license?

**Comment by sergejsha** [comment]
The change is on the was in release 0.4
